# Generated by Django 5.0.6 on 2024-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_name',
            field=models.CharField(blank=True, help_text='Укажите username телеграмм', max_length=128, null=True, verbose_name='Имя телеграм'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Укажите почту', max_length=254, unique=True, verbose_name='Почта'),
        ),
    ]
