# Generated by Django 5.0.6 on 2024-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_username_user_tg_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите ID телеграм', max_length=64, null=True, verbose_name='ID телеграм'),
        ),
    ]
