# Generated by Django 5.0.6 on 2024-06-13 14:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название привычки', max_length=64, verbose_name='Название')),
                ('location', models.CharField(help_text='Укажите место, в котором необходимо выполнять привычку', max_length=256, verbose_name='Место')),
                ('action_time', models.TimeField(help_text='Укажите время, когда необходимо выполнять привычку', verbose_name='Время привычки')),
                ('action', models.CharField(help_text='Укажите что нужно делать', max_length=512, verbose_name='Действие')),
                ('pleasant', models.BooleanField(default=False, help_text='Привычка является приятной ?', verbose_name='Приятная привычка')),
                ('periodicity', models.CharField(choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], default='D', help_text='Выберите периодичность выполнения', max_length=1, verbose_name='Периодичность')),
                ('award', models.CharField(blank=True, help_text='Укажите чем вы хотите себя вознаградить за выполнение привычки', max_length=256, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(default=datetime.timedelta(seconds=300), help_text='Укажите время, в течение которого Вы будете выполнять привычку', verbose_name='Время на выполнение')),
                ('public', models.BooleanField(default=False, help_text='Опубликовать привычку ?', verbose_name='Опубликовать')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('id',),
            },
        ),
    ]
