# Generated by Django 5.0.6 on 2024-06-15 09:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.DurationField(default=datetime.timedelta(seconds=120), help_text='Укажите время, в течение которого Вы будете выполнять привычку', verbose_name='Время на выполнение'),
        ),
    ]
