# Generated by Django 5.0.6 on 2024-06-15 10:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье'), ('Everyday', 'Каждый день')], default='Everyday', help_text='Выберите периодичность выполнения', max_length=10, verbose_name='Периодичность'),
        ),
    ]
