# Generated by Django 5.0.6 on 2024-06-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0010_alter_habit_periodicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='pleasant_habit',
            new_name='is_pleasant',
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Свяжите полезную привычку с приятной', limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка'),
        ),
    ]
