# Generated by Django 5.0.6 on 2024-06-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0017_alter_habit_periodicity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='public',
            new_name='is_public',
        ),
    ]
