# Generated by Django 5.0.6 on 2024-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0019_habit_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.CharField(choices=[('1h', 'За 1 час'), ('30m', 'За 30 минут'), ('10m', 'За 15 минут'), ('5m', 'За 5 минут'), ('no', 'Не напоминать')], default='10m', help_text='Выберите время напоминания', max_length=5, verbose_name='Напоминание'),
        ),
    ]
