# Generated by Django 5.0.6 on 2024-06-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0020_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='send_status',
            field=models.BooleanField(default=False, verbose_name='Статус отправки'),
        ),
    ]
