# Generated by Django 5.0.6 on 2024-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0021_habit_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье'), ('30', 'Каждый день')], default='30', help_text='Выберите периодичность выполнения', max_length=10, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.CharField(choices=[('60', 'За 1 час'), ('30', 'За 30 минут'), ('10', 'За 15 минут'), ('5', 'За 5 минут'), ('0', 'Не напоминать')], default='10', help_text='Выберите время напоминания', max_length=5, verbose_name='Напоминание'),
        ),
    ]
