# Generated by Django 5.0.6 on 2024-06-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0022_alter_habit_periodicity_alter_habit_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reminder_time',
            field=models.CharField(choices=[('60', 'За 1 час'), ('30', 'За 30 минут'), ('10', 'За 10 минут'), ('5', 'За 5 минут'), ('0', 'Не напоминать')], default='10', help_text='Выберите время напоминания', max_length=5, verbose_name='Напоминание'),
        ),
    ]
